name: CI

on:
  pull_request:
    branches: [main]

jobs:
  Exec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ".go-version"
          cache-dependency-path: "go.sum"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
      - run: go install github.com/mfridman/tparse@v0.18.0
      - run: |
          set -o pipefail
          go test -race -cover -json ./... | tparse --all